version: "3.4"

services:
  ros2_playground_test_rosbridge:
    build:
      context: ../
      dockerfile: ./ros_bridge/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: ros2_playground/test_rosbridge:galactic
    container_name: ros2_playground_rosbridge
    network_mode: "host"           # access to host's network
    stdin_open: true                # docker run -i
    tty: true                       # docker run -t
    privileged: true                # Needed for /dev volume
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}             # Pass the display for GUI
      - QT_X11_NO_MITSHM=1             # Needed by QT programs
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix:rw
       - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
       - ../ros2_ws/src:/home/ros/workspaces/ros2_ws/src
